# Generated by Django 3.2.8 on 2021-10-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_original', models.FileField(upload_to='%Y/%m/%d/', verbose_name='Imagem Original')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Valor')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('imagem_tratada', models.FileField(upload_to='%Y/%m/%d/', verbose_name='Imagem Tratada')),
                ('imagem_copilada', models.FileField(upload_to='%Y/%m/%d/', verbose_name='Imagem Copilada')),
            ],
        ),
    ]
